name: turtlebot3c
version: '0.1'
summary: Turtlebot3c core snap
description: |
  This snap automatically spawn a roscore and the core components for the
  Turtlebot3.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18 # Melodic

architectures:
  - build-on: [amd64, arm64, armhf]

parts:
  workspace:
    plugin: catkin
    include-roscore: true
    source: .
    rosinstall-files: ['turtlebot3c.rosinstall']
    stage-packages: [libslang2, freeglut3]
    build-packages: [distro-info-data] # distro-info-data is necessary on some remote e.g. CI

apps:

  core:
    daemon: simple
    environment:
      TURTLEBOT3_MODEL: waffle_pi
    command: roslaunch turtlebot3c_bringup turtlebot3c_bringup.launch
    plugs: [network, network-bind, raw-usb]

  teleop:
    environment:
      TURTLEBOT3_MODEL: waffle_pi
    command: roslaunch turtlebot3c_teleop turtlebot3c_teleop.launch
    plugs: [network, network-bind, joystick]

  mapping:
   environment:
     TURTLEBOT3_MODEL: waffle_pi
   command: rosrun turtlebot3c_2dnav mapping_manager
   plugs: [network, network-bind]

  navigation:
   environment:
     TURTLEBOT3_MODEL: waffle_pi
   command: roslaunch turtlebot3c_2dnav turtlebot3c_navigation.launch
   plugs: [network, network-bind]
